# Generated by Django 6.1.1 on 2026-09-13 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: 8 000 000 so‘m', max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='Например: Ахмад · 12.03.2026', max_length=160, verbose_name='Подпись')),
                ('image', models.ImageField(upload_to='reviews/proofs/', verbose_name='Скриншот')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Доказательство оплаты',
                'verbose_name_plural': 'Доказательства оплаты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('role', models.CharField(blank=True, help_text='Например: Курьер · 8 месяцев · Ташкент', max_length=120, verbose_name='Роль / должность')),
                ('video', models.FileField(help_text='MP4, H.264, вертикальное 9:14, до 5 МБ', upload_to='reviews/videos/', verbose_name='Видео')),
                ('poster', models.ImageField(blank=True, help_text='Картинка, которая покажется до старта видео', null=True, upload_to='reviews/posters/', verbose_name='Превью (необязательно)')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Проверено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Видео-отзыв',
                'verbose_name_plural': 'Видео-отзывы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bag',
            name='narx',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Narx (so'm)"),
        ),
    ]
