# Generated by Django 6.1.1 on 2026-09-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_paymentproof_videoreview_alter_bag_narx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentProof',
        ),
    ]
